on:
  webhook:
    method: post
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body
          
#       - name: Send email
#         uses: dawidd6/action-send-mail@v3.6.0
#         with:
#           # Required mail server address:
#           server_address: smtp.gmail.com
#           # Required mail server port:
#           server_port: 465
#           # Optional (recommended): mail server username:
#           username: ${{secrets.MAIL_USERNAME}}
#           # Optional (recommended) mail server password:
#           password: ${{secrets.MAIL_PASSWORD}}
#           # Required mail subject:
#           subject: Github Actions job result
#           # Required recipients' addresses:
#           to: obiwan@example.com,yoda@example.com
#           # Required sender full name (address can be skipped):
#           from: Luke Skywalker # <pierre@etc-nyc.com>
#           # Optional whether this connection use TLS (default is true if server_port is 465)
#           secure: true
#           # Optional plain body:
#           body: Build job of ${{github.repository}} completed successfully!
#           # Optional unsigned/invalid certificates allowance:
#           ignore_cert: true
#           # Optional priority: 'high', 'normal' (default) or 'low'
#           priority: low

